micronaut:
  application:
    name: livrariaSub
server:
  cors:
    enabled: true
  port: 8080
endpoints:
  health:
    enabled: true
cassandra:
  default:
    clusterName: '"cassandra"'
    contactPoint: '"localhost"'
    port: 9042
    maxSchemaAgreementWaitSeconds: 20
    ssl: true
    consistencylevel: LOCAL_ONE
nats:
  addresses: localhost:4222
  username: guest
  password: guest